/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AccessTokenSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AccessTokenTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "LinkTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RefreshTokenSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}